ALTER TABLE lists ADD COLUMN preview_day INTEGER NOT NULL DEFAULT 0;
ALTER TABLE lists ADD COLUMN preview_count INTEGER NOT NULL DEFAULT 0 CHECK (preview_count BETWEEN 0 AND 60);
ALTER TABLE lists ADD COLUMN preview_at INTEGER NOT NULL DEFAULT 0;
